### ISSUE TITLE
loadCSS and PageSpeed Insights "blocking CSS"

### ISSUE THREAD

**Issue by rarkins** [filamentgroup/loadCSS#53]
Thanks for all the great tools, including this one. I know user experience is more important than PageSpeed Insights score, and this is not a PageSpeed troubleshooting forum, however I'd like to check that I'm not doing something wrong with loadCSS before blaming Pagespeed.

Here's the entirety of my code, which is located in the `<head>`:
```html
<script>
  function loadCSS(a,b,c){
    "use strict";function g(){for(var b,e=0;e<f.length;e++)f[e].href&&f[e].href.indexOf(a)>-1&&(b=!0);b?d.media=c||"all":setTimeout(g)}var d=window.document.createElement("link"),e=b||window.document.getElementsByTagName("script")[0],f=window.document.styleSheets;return d.rel="stylesheet",d.href=a,d.media="only x",e.parentNode.insertBefore(d,e),g(),d
  }
  loadCSS("/public/fontface-1f24f01.css");
</script>
<script>
  loadCSS("/public/bootstrap-ebf66f6.css");
  loadCSS("/public/global-e4c2321.css");
  loadCSS("/public/condo-01c4f25.css");
</script>
```

I then also have critical CSS inlined in the `<head>`, and the user experience is great (i.e. works as expected and promised by @scottjehl!). However, PageSpeed Insights reports:
> Your page has 4 blocking CSS resources. This causes a delay in rendering your page.

And then lists those four .css files from above.

I'm satisfied that user experience is vastly improved but disappointed if this is a "false positive" from PageSpeed. Any suggestions?

**Comment by scottjehl** [comment]
I've seen this from time to time as well (not on any sites I've developed but others have mentioned it before). 

Can you paste the entire `head` to make sure there's nothing else in play?

I suspect it is a bug in PSI. It doesn't happen with many sites that use loadCSS, for example here:
https://developers.google.com/speed/pagespeed/insights/?url=filamentgroup.com&tab=mobile

**Comment by rarkins** [comment]
Here is an example:
```html
<head><meta charset="utf-8"><title>Aalto - Singapore condo review</title><meta property="og:title" content="Aalto - Singapore condo review"><meta name="twitter:title" content="Aalto - Singapore condo review"><meta name="description" content="Aalto is a mid-sized condo in Singapore's Marine Parade area. It was built in 2010 and is well known for ..."><meta property="og:description" content="Aalto is a mid-sized condo in Singapore's Marine Parade area. It was built in 2010 and is well known for ..."><meta name="twitter:description" content="Aalto is a mid-sized condo in Singapore's Marine Parade area. It was built in 2010 and is well known for ..."><meta name="keywords" content="Aalto, condo rent history, Singapore condo, condominium, Rent in Singapore"><meta name="title" data-type="string" content="Aalto" class="swiftype"><meta name="image" data-type="enum" content="https://images.keylocation.sg/condo/120x120/aalto.jpg" class="swiftype"><link rel="shortcut icon" href="/public/assets/images/favicon/favicon-1bf5130.ico"><link rel="apple-touch-icon-precomposed" href="/public/assets/images/favicon/apple-touch-icon-precomposed-c3706db.png"><link rel="apple-touch-icon" href="/public/assets/images/favicon/apple-touch-icon-4b946bd.png"><link rel="apple-touch-icon" sizes="57x57" href="/public/assets/images/favicon/apple-touch-icon-57x57-0b9b6a6.png"><link rel="apple-touch-icon" sizes="114x114" href="/public/assets/images/favicon/apple-touch-icon-114x114-9545b7b.png"><link rel="apple-touch-icon" sizes="60x60" href="/public/assets/images/favicon/apple-touch-icon-60x60-972778b.png"><link rel="apple-touch-icon" sizes="120x120" href="/public/assets/images/favicon/apple-touch-icon-120x120-c3766ac.png"><link rel="apple-touch-icon" sizes="72x72" href="/public/assets/images/favicon/apple-touch-icon-72x72-344c7b4.png"><link rel="apple-touch-icon" sizes="144x144" href="/public/assets/images/favicon/apple-touch-icon-144x144-212091e.png"><link rel="apple-touch-icon" sizes="76x76" href="/public/assets/images/favicon/apple-touch-icon-76x76-89b25f7.png"><link rel="apple-touch-icon" sizes="152x152" href="/public/assets/images/favicon/apple-touch-icon-152x152-4b946bd.png"><link rel="icon" type="image/png" sizes="192x192" href="/public/assets/images/favicon/favicon-192x192-cecb769.png"><link rel="icon" type="image/png" sizes="160x160" href="/public/assets/images/favicon/favicon-160x160-8749b27.png"><link rel="icon" type="image/png" sizes="96x96" href="/public/assets/images/favicon/favicon-96x96-326c776.png"><link rel="icon" type="image/png" sizes="16x16" href="/public/assets/images/favicon/favicon-16x16-a22ebb2.png"><link rel="icon" type="image/png" sizes="32x32" href="/public/assets/images/favicon/favicon-32x32-bd9509f.png"><meta name="msapplication-TileColor" content="#00a300"><meta name="msapplication-TileImage" content="/public/assets/images/favicon/mstile-144x144-66aff9d.png"><meta name="msapplication-config" content="/public/assets/images/favicon/browserconfig-254bf08.xml"><link rel="canonical" href="https://keylocation.sg/condos/aalto"><meta property="og:image" content="/public/assets/images/favicon/apple-touch-icon-4b946bd.png"><meta name="twitter:image:src" content="/public/assets/images/favicon/apple-touch-icon-4b946bd.png"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no"><meta property="og:type" content="website"><meta property="og:url" content="https://keylocation.sg/condos/aalto"><meta property="og:site_name" content="Key Location"><meta property="og:locale" content="en_US"><meta name="twitter:card" content="summary"><meta name="twitter:site" content="@keylocation"><meta name="twitter:domain" content="keylocation.sg"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><script>window._trackJs = {enabled: true, token: 'fdbfb05c50514b0bbd34ee206c9c911e', userId: ''};var heapToken = 579102418;var FHChat = {product_id: '892e264bd1c7'};var hotjarToken = 10361;</script><!-- - loadCSS--><script>function loadCSS(a,b,c){"use strict";function g(){for(var b,e=0;e<f.length;e++)f[e].href&&f[e].href.indexOf(a)>-1&&(b=!0);b?d.media=c||"all":setTimeout(g)}var d=window.document.createElement("link"),e=b||window.document.getElementsByTagName("script")[0],f=window.document.styleSheets;return d.rel="stylesheet",d.href=a,d.media="only x",e.parentNode.insertBefore(d,e),g(),d}
loadCSS("/public/fontface-1f24f01.css");
</script><script async src="/public/condo-1bd7f9f.js"></script><script>loadCSS("/public/bootstrap-ebf66f6.css");
loadCSS("/public/global-e4c2321.css");
loadCSS("/public/condo-01c4f25.css");
</script><style>html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}header,main,nav{display:block}a{background-color:transparent}strong{font-weight:700}h1{margin:.67em 0}img{border:0}svg:not(:root){overflow:hidden}hr{box-sizing:content-box;height:0}button,input{color:inherit;font:inherit;margin:0}button{overflow:visible;text-transform:none;-webkit-appearance:button;cursor:pointer}button::-moz-focus-inner,input::-moz-focus-inner{border:0;padding:0}*{box-sizing:border-box}*:before,*:after{box-sizing:border-box}html{-webkit-tap-highlight-color:rgba(0,0,0,0)}body{font-family:'Open Sans',sans-serif;font-size:16px;line-height:1.42857143;color:#777;background-color:#fff}input,button{font-family:inherit;font-size:inherit;line-height:inherit}a{color:#337ab7;text-decoration:none}img{vertical-align:middle}hr{margin-top:22px;margin-bottom:22px;border:0;border-top:1px solid #eee}.sr-only{position:absolute;width:1px;height:1px;margin:-1px;padding:0;overflow:hidden;clip:rect(0,0,0,0);border:0}h1,h2,h3{font-family:inherit;font-weight:500;line-height:1.1;color:inherit;margin-top:22px;margin-bottom:11px}h1{font-size:41px}h2{font-size:34px}h3{font-size:28px}p{margin:0 0 11px}ul{margin-top:0;margin-bottom:11px}.container{margin-right:auto;margin-left:auto;padding-left:15px;padding-right:15px}@media (min-width:768px){.container{width:750px}}@media (min-width:992px){.container{width:970px}}@media (min-width:1200px){.container{width:1170px}}.container-fluid{margin-right:auto;margin-left:auto;padding-left:15px;padding-right:15px}.row{margin-left:-15px;margin-right:-15px}.col-sm-4,.col-sm-6,.col-lg-10,.col-xs-12,.col-sm-12{position:relative;min-height:1px;padding-left:15px;padding-right:15px}.col-xs-12{float:left;width:100%}@media (min-width:768px){.col-sm-4,.col-sm-6{float:left}.col-sm-12{float:left;width:100%}.col-sm-6{width:50%}.col-sm-4{width:33.33333333%}}@media (min-width:1200px){.col-lg-10{float:left;width:83.33333333%}.col-lg-offset-1{margin-left:8.33333333%}}label{max-width:100%;margin-bottom:5px;font-weight:700}label,.btn{display:inline-block}.btn{margin-bottom:0;font-weight:400;text-align:center;vertical-align:middle;-ms-touch-action:manipulation;touch-action:manipulation;cursor:pointer;background-image:none;border:1px solid transparent;white-space:nowrap;padding:6px 12px;font-size:16px;line-height:1.42857143;border-radius:4px;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;user-select:none}.btn-default{color:#333;background-color:#fff;border-color:#ccc}.btn-lg{padding:10px 16px;font-size:20px;line-height:1.3333333;border-radius:6px}.btn-xs{padding:1px 5px;font-size:14px;line-height:1.5;border-radius:3px}.btn-block{display:block;width:100%}.fade{opacity:0;transition:opacity .15s linear}.collapse{display:none;visibility:hidden}.btn-group{position:relative;display:inline-block;vertical-align:middle}.btn-group>.btn{float:left;position:relative}.btn-group .btn-group+.btn-group{margin-left:-1px}.btn-group>.btn:first-child{margin-left:0}.btn-group>.btn-group{float:left}.btn-group>.btn-group:not(:first-child):not(:last-child)>.btn{border-radius:0}.btn-group>.btn-group:first-child:not(:last-child)>.btn:last-child{border-bottom-right-radius:0;border-top-right-radius:0}.btn-group>.btn-group:last-child:not(:first-child)>.btn:first-child{border-bottom-left-radius:0;border-top-left-radius:0}.btn-group-justified{display:table;width:100%;table-layout:fixed;border-collapse:separate}.btn-group-justified>.btn-group{float:none;display:table-cell;width:1%}.btn-group-justified>.btn-group .btn{width:100%}.nav{margin-bottom:0;padding-left:0;list-style:none}.nav>li,.nav>li>a{position:relative;display:block}.nav>li>a{padding:10px 15px}.navbar{position:relative;min-height:50px;margin-bottom:22px;border:1px solid transparent}@media (min-width:768px){.navbar{border-radius:4px}}@media (min-width:768px){.navbar-header{float:left}}.navbar-collapse{overflow-x:visible;padding-right:15px;padding-left:15px;border-top:1px solid transparent;box-shadow:inset 0 1px 0 rgba(255,255,255,.1);-webkit-overflow-scrolling:touch}@media (min-width:768px){.navbar-collapse{width:auto;border-top:0;box-shadow:none}.navbar-collapse.collapse{display:block!important;visibility:visible!important;height:auto!important;padding-bottom:0;overflow:visible!important}.navbar-fixed-top .navbar-collapse{padding-left:0;padding-right:0}}.navbar-fixed-top .navbar-collapse{max-height:340px}@media (max-device-width:480px) and (orientation:landscape){.navbar-fixed-top .navbar-collapse{max-height:200px}}.container-fluid>.navbar-collapse{margin-right:-15px;margin-left:-15px}@media (min-width:768px){.container-fluid>.navbar-collapse{margin-right:0;margin-left:0}}.navbar-fixed-top{position:fixed;right:0;left:0;z-index:1030}@media (min-width:768px){.navbar-fixed-top{border-radius:0}}.navbar-fixed-top{top:0;border-width:0 0 1px}.navbar-brand{float:left;padding:14px 15px;font-size:20px;line-height:22px;height:50px}.navbar-brand>img{display:block}@media (min-width:768px){.navbar>.container-fluid .navbar-brand{margin-left:-15px}}.navbar-toggle{position:relative;float:right;margin-right:15px;padding:9px 10px;margin-top:8px;margin-bottom:8px;background-color:transparent;background-image:none;border:1px solid transparent;border-radius:4px}@media (min-width:768px){.navbar-toggle{display:none}}.navbar-nav{margin:7px -15px}.navbar-nav>li>a{padding-top:10px;padding-bottom:10px;line-height:22px}@media (min-width:768px){.navbar-nav{float:left;margin:0}.navbar-nav>li{float:left}.navbar-nav>li>a{padding-top:14px;padding-bottom:14px}}.navbar-default{background-color:#f8f8f8;border-color:#e7e7e7}.navbar-default .navbar-brand,.navbar-default .navbar-nav>li>a{color:#777}.navbar-default .navbar-toggle{border-color:#ddd}.navbar-default .navbar-collapse{border-color:#e7e7e7}.modal{overflow:hidden;display:none;position:fixed;top:0;right:0;bottom:0;left:0;z-index:1040;-webkit-overflow-scrolling:touch;outline:0}.modal.fade .modal-dialog{-webkit-transform:translate(0,-25%);-ms-transform:translate(0,-25%);transform:translate(0,-25%);transition:-webkit-transform .3s ease-out;transition:transform .3s ease-out}.modal-dialog{position:relative;width:auto;margin:10px}.modal-content{position:relative;background-color:#fff;border:1px solid #999;border:1px solid rgba(0,0,0,.2);border-radius:6px;box-shadow:0 3px 9px rgba(0,0,0,.5);background-clip:padding-box;outline:0}.modal-header{padding:15px;border-bottom:1px solid #e5e5e5;min-height:16.42857143px}.modal-body{position:relative;padding:15px}.modal-footer{padding:15px;text-align:right;border-top:1px solid #e5e5e5}@media (min-width:768px){.modal-dialog{width:600px;margin:30px auto}.modal-content{box-shadow:0 5px 15px rgba(0,0,0,.5)}}.container:before,.container:after,.container-fluid:before,.container-fluid:after,.row:before,.row:after,.nav:before,.nav:after,.navbar:before,.navbar:after,.navbar-header:before,.navbar-header:after,.navbar-collapse:before,.navbar-collapse:after,.modal-footer:before,.modal-footer:after{content:" ";display:table}.container:after,.container-fluid:after,.row:after,.nav:after,.navbar:after,.navbar-header:after,.navbar-collapse:after,.modal-footer:after{clear:both}.hidden{visibility:hidden!important}.hidden,.visible-xs{display:none!important}@media (max-width:767px){.visible-xs{display:block!important}}header .header__default{background:#fff;border:none;min-height:45px;z-index:1030;box-shadow:0 1px 10px rgba(0,0,0,.1);transition:.4s margin-top}header .header__toggle{border:0;width:35px;height:35px;margin:5px 0}header .header__toggle .hamburger{position:absolute;top:0;left:0}header .header__brand{padding:0;position:absolute;margin-top:5px}header .header__logo{height:35px;width:188px}header .header__nav{float:right;margin-right:70px}header .header__nav li a{font-size:17px;height:45px;line-height:45px;text-transform:uppercase;text-align:center;padding-top:0;padding-bottom:0}header .header__nav .user{margin:10px 5px 0 0}.morph{width:36px;height:36px;position:absolute;overflow:hidden;right:30px;top:5px;z-index:2;background:#fff;border:2px solid #7dc24f;box-sizing:border-box;-webkit-transform-origin:100% 0;-ms-transform-origin:100% 0;transform-origin:100% 0;transition:.5s width,.5s height,.5s right,.5s top,.1s border ease-in-out}.header-search{margin:0 auto;width:80%;height:40px;position:relative;transition:.5s}.morph__results{width:80%;text-align:center;margin:25px auto 45px;opacity:0}.header-search__close{position:absolute;top:20px;right:40px;width:36px;height:36px;cursor:pointer;-webkit-transform:scale3d(0,0,1);transform:scale3d(0,0,1)}.header-search__close:before,.header-search__close:after{content:'';position:absolute;width:2px;top:0;left:50%;height:100%;background:#80b83d;opacity:.4;transition:.3s ease-in-out}.header-search__close:before{-webkit-transform:rotate(-45deg);-ms-transform:rotate(-45deg);transform:rotate(-45deg)}.header-search__close:after{-webkit-transform:rotate(45deg);-ms-transform:rotate(45deg);transform:rotate(45deg)}.morph--overlay{position:fixed;top:0;left:0;width:100%;height:0;background:rgba(0,0,0,.5);opacity:0;transition:opacity .5s}.header-search__icon{cursor:pointer;position:absolute;top:1px;right:2px;z-index:100;padding:0;width:25px;height:25px;margin-top:3px;margin-right:-1px;transition:width .5s,height .5s,top .5s,margin .5s,fill .5s,opacity .3s}.header-search__input{width:100%;height:100%;font-size:5.5em;color:#80b83d;background:0 0;border:0;outline:0;opacity:0;padding:0 20% 0 0;-webkit-backface-visibility:hidden;backface-visibility:hidden;-webkit-transform:rotateX(-90deg);transform:rotateX(-90deg)}.header-search__input::-webkit-input-placeholder{color:gray}.header-search__input::-moz-placeholder{color:gray}.header-search__input:-ms-input-placeholder{color:gray}@media (min-width:768px){header .header__brand{margin-left:15px!important}}@media (max-width:767px){header .header__collapse{position:absolute;background:#fff;width:190px;padding:0;right:0;box-shadow:0 6px 12px rgba(0,0,0,.175)}header .header__nav{float:none;margin:0}header .nav-container{padding:0 5px}.morph{right:55px;border:2px solid #fff}.header-search__input{font-size:2.5em!important}.header-search__close{top:5px;right:15px;width:25px;height:25px}}@media (max-width:480px){.morph__results{margin:0 auto}}.icon--16{height:16px;width:16px}.icon--25{height:25px;width:25px}.icon--36{height:36px;width:36px}.icon--white{fill:#fff}.icon--darkgray{fill:#616161}.icon--green{fill:#80b83d}html{-webkit-font-smoothing:antialiased;height:100%;font-size:18px!important}body{padding-top:88px;height:100%}body h1{font-size:3em;color:#000;font-style:normal;letter-spacing:.1em}body h2{color:gray;font-size:1.5rem}body h3{color:#000;font-size:1.2rem}.wrapper{height:100%;width:100%;position:relative;display:table;table-layout:fixed}@media (max-width:767px){body{padding-top:65px}}body{background:#c9edec!important}.condo-detail{background:#fff}.condo-detail .condo-detail__header{-webkit-perspective:1100;perspective:1100;margin-top:-45px;padding:0}.condo-detail .header__cityscape{background:url(/public/assets/images/condo/cityscape-header-afdcd4c.svg) no-repeat center,radial-gradient(#fff,#c9edec 70%),#c9edec;background-size:cover;height:300px}.condo-detail .header__description{background:#6bb83b;color:#fff;text-align:center;padding:40px 40px 20px}.condo-detail .description__polaroid{background:#fff;width:320px;padding:10px;position:absolute;left:50%;margin:-315px 0 0 -160px;transition:-webkit-transform 1.2s cubic-bezier(.65,1.85,.03,.8);transition:transform 1.2s cubic-bezier(.65,1.85,.03,.8);-webkit-backface-visibility:hidden;backface-visibility:hidden;-webkit-transform:rotateY(0);transform:rotateY(0);z-index:3}.condo-detail .polaroid__condo-name{font-size:1.5em;background:#00551a;color:#fff;font-weight:700;text-transform:uppercase;margin:0}.condo-detail .polaroid__condo-name .name{display:block}.condo-detail .polaroid__condo-name .name__1{padding:25px 0;min-height:76px}.condo-detail .polaroid__condo-name .name__2{background:#6bb83b;padding:35px 0;height:97px;line-height:27px}.condo-detail .polaroid__condo-name .name__3{padding:25px 5px 90px;min-height:141px}.condo-detail .polaroid__condo-thumbnail{width:120px;height:120px;margin:-65px auto -2px;border-radius:10px;background:#6bb83b;border:2px solid #fff}.condo-detail .description__social{margin-top:87px;margin-bottom:10px}.condo-detail .social__icon{border:2px solid #fff;border-radius:10px;width:35px;height:35px;display:inline-block;margin:0 10px;line-height:44px}@media (max-width:767px){.condo-detail .condo-detail__header{margin-top:-19px}.condo-detail .header__description{padding-left:20px;padding-right:20px}}@media (max-width:320px){.condo-detail .description__polaroid{margin-top:-340px;margin-bottom:60px}.condo-detail .polaroid__condo-thumbnail{position:absolute;left:50%;margin-left:-60px}}.condo-detail .condo-detail__block{background-color:#ececec;padding:15px}.condo-detail .block__header,.condo-detail .block__subheader{color:#fff;text-align:center;text-transform:uppercase;margin:0}.condo-detail .block__header{font-size:38px;background-color:#616161;padding:22px 0}.condo-detail .block__subheader{background-color:#6bb83b;padding:10px 0}.condo-detail .block__property{margin:15px 0;padding:15px;border:1px solid silver;border-top-left-radius:25px}.condo-detail .block__property span{font-weight:700}.condo-detail .location__map{padding:0}.condo-detail .map{width:100%;height:290.674173px}.condo-detail .map__dot{position:absolute;top:0;left:0}.condo-detail .schools__scenery{background:radial-gradient(#fff,#c9edec 70%),#c9edec;width:100%}#redirect-modal .btn-block{margin-top:8px;color:#fff;background:#80b83d;font-size:19px}#redirect-modal p{margin:0 0 15px;text-align:center;line-height:25px}</style></head>
```
Excerpt from https://keylocation.sg/condos/aalto

I noticed that Google now have their own code snippet here: https://developers.google.com/speed/docs/insights/OptimizeCSSDelivery

In it they do the style insertion using either `requestAnimationFrame` or on load.

**Comment by rarkins** [comment]
FYI I adapted the Google-recommended JS to be a drop-in replacement for loadCSS and found that page rendering blocks waiting on my font CSS. Which probably is another sign that I should try [font events](http://www.filamentgroup.com/lab/font-events.html) again though.

**Comment by rarkins** [comment]
Something strange is that when I attempt to use Google's snippet, it blocks rendering every time. e.g. I modified the above to load just the bootstrap CSS file using Google's script:
```html
<script>var cb = function () {
  var l = document.createElement('link');
  l.rel = 'stylesheet';
  l.href = '/public/bootstrap-82c23a0.css';
  var h = document.getElementsByTagName('script')[0];
  h.parentNode.insertBefore(l, h);
};
var raf = requestAnimationFrame || mozRequestAnimationFrame ||
  webkitRequestAnimationFrame || msRequestAnimationFrame;
if (raf) raf(cb);
else window.addEventListener('load', cb);
loadCSS("/public/global-55c4862.css");
loadCSS("/public/condo-7b43541.css");
```

Chrome and Chrome Canary both block rendering on this, although in slightly different ways.

**Comment by rarkins** [comment]
Back to PSI and LoadCSS - I'm beginning to suspect a bug in PSI. Observed today:

1. Home page (https://keylocation.sg) does not get blocking CSS warning but condo pages (e.g. https://keylocation.sg/condos/aalto) do. The exact same loadCSS approach is used in both.
2. Sometimes when running PSI the blocking CSS warning is made for mobile and not desktop. e.g.
![critical-css](https://cloud.githubusercontent.com/assets/6311784/7332618/00858ef4-eb48-11e4-80b6-247c4626fe3d.gif)

**Comment by scottjehl** [comment]
I've been talking to the PSI team and it does seem that these are bugs in their service. They don't show up in all cases where loadCSS is in play, and in every case that I've investigated, a webpagetest timeline will show that the named resources are indeed non-blocking.

So, I'm not sure what to recommend other than testing  to be make things are working right if PSI's recommendations seem fishy. Thanks!

**Comment by dereckmartin** [comment]
Thank you for this insight as of today this is still buggy in PSI.  It has really been bugging why PSI is reporting it as blocking.  

I only have two files loaded a JS and a CSS file for a meteor app.  I was able to async the JS, and use loadCSS for the css file.  Both end up at the bottom of the page, and there is nothing in the title except a meta tag and a title tag.

PSI still reports the css as blocking on mobile.

**Comment by juliandormon** [comment]
I can confirm as of today that it still is buggy. I was not having issues last week and now all of sudden, PSI does not like our css files loaded using loadCSS().  Thanks so much for this great code by the way!

**Comment by renettarenula** [comment]
This happens to me when I add loadCSS inline JS code AFTER my inline critical CSS code. The warning on PSI went away when I move it before the inline CSS. 

Putting a small inline JS code before the CSS style tag is better as well since it doesn't block CSSOM. For those interested, you can read about it more here: https://www.igvita.com/2014/05/20/script-injected-async-scripts-considered-harmful/

**Comment by rarkins** [comment]
@renettarenula it seems like there's probably "something" about ordering that might fix PageSpeed scores, but it doesn't seem to be as deterministic as "critical CSS styles after loadCSS JS". My critical CSS styes are placed immediately before `</head>` and all loadCSS JS is before it, and I still get blocking CSS warnings from PageSpeed Insights.

**Comment by rsteinwand** [comment]
My setup is:
<head>
<link rel=preload to postloaded css>
CriticalCSS
Async Defer scripts
</head><body>
Script to load it all at the bottom.
</body>

PSI Score: 99% (-1% for Google Analytics).

http://www.intercepteft.com/searchsite.aspx

**Comment by rarkins** [comment]
@rsteinwand could you confirm if you're using both loadcss + preload Polyfill, and also where exactly those scripts are relative to the other code you mention?

**Comment by rarkins** [comment]
Specifically, I'm a little confused by your code description when combined with this earlier statement:

> This happens to me when I add loadCSS inline JS code AFTER my inline critical CSS code. The warning on PSI went away when I move it before the inline CSS. 

I had assumed you invoked loadCSS() before critical CSS. But did you mean you inlined the loadCSS code before critical but only invoked it later?

**Comment by rsteinwand** [comment]
Sorry, ignore my comments. The preload css link is there, but a different css loader is used on that page (like the rest of the site). Apparently the page got clobbered and the script is no longer there.

**Comment by rsteinwand** [comment]
@rarkins: file has been updated. I have two files with similar names and referred to the wrong one. Both have been updated to use loadCSS.

Yes, loadCSS + polyfill is inlined at the bottom of the page, before `</body>`
Critical css is inlined after the rel=preloaded post-loaded css.

These are the only two files on this site with loadCSS. Neither has blocking issue.
http://www.intercepteft.com/searchsite.aspx
http://www.intercepteft.com/searchsite.html

**Comment by wilcoverhoeven** [comment]
I had the same problem. It was driving me nuts all morning, but I managed to fix it

For me it was the critical css that was causing the problem. The critical css did not contain the background image for the header of the site, so it was missing some styles for the "above the fold" html.

I guess that pagespeed considers this blocking because the "above the fold" html could only be completely styled by loading the css file.

**Comment by hummal** [comment]
Had the same problem with PSI and loadCSS. After putting the whole code (Inlined loadCSS base code and the call to loadCSS(PATHTOCSSFILE) **before** the inlined CSS in the head the pagespeed comes back to 88 from 69. 
I made some thoughts about that. Is it possible that the inlined atf css (if it is very much of it) could not be rendered/painted completely by the browser before it comes to the end of body tag where the loadCSS call loads the asyn css. After this css is completely loaded it forces a redraw which blocks the rendering again. 

In short: the inline CSS rendering was not completed while the async CSS was loaded and forced a redraw which causes the blocking.

**Comment by malcocerGit** [comment]
@hummal You're right, I remove my background from the critical css and leave on the loadCSS, wins 2-6 points.

**Comment by fatjester** [comment]
@hummal and @malcocerGit - Additional thanks for that info.  I was also having issues with Page Insights and loadCSS thinking it was a google bug.  I also had some elements that were causing a redraw and google was penalizing for that.  Your comments helped me solve a number of my PSI issues.

**Comment by uspriya2006** [comment]
Even after reordering the loadCss and criticalCss I am still seeing this issue. There are 4 css resources on our page, PSI was showing 3 as render blocking, even though all 4 are loaded using loadCSS. After reordering (loadCss first, followed by inlined critical css) it is now showing 1 render blocking css resource and only on mobile. Is this an issue in page speed insights or something I could do to fix this in my code?

**Comment by fatjester** [comment]
@uspriya2006 - do you have a url to look at?

**Comment by uspriya2006** [comment]
This is the url of the page www.expedia.co.uk

**Comment by fatjester** [comment]
@uspriya2006, you might want to take a close look at the expedia-responsive.css stylesheet, particularly at the elements in your media queries - since that's that's the stylesheet flagged only in mobile view.  The fact your other styles aren't flagged (or even this one in desktop view) shows that the script is working, and it's another element likely triggering this.

@hummal and @malcocerGit 's comments above clued me into that Google will flag an async stylesheet if it triggers a redraw that is dependent on loading something in above-the-fold content - particularly if it happens before the entire page has been rendered (and this all happens in microseconds, so it can be tricky to debug). 

In my case, it was items that referenced a custom font family - and once the async style noted I needed a font - the browser had to pause, download the font, then redraw.  I ended up using fontfaceobserver to load the fonts behind the scenes, then changing the body class to a fonts-loaded, so the fonts were there at the time the items needed them.  I don't think its the redraw entirely that triggers this warning, but a redraw that is dependent on downloading something.

You might want to make a very simple version of this page - with the same content source code, but only loading this one stylesheet.  It might be easier to debug that way.

Good luck!

**Comment by malcocerGit** [comment]
@fatjester Thanks for the advice, I will try it that and share my result. Since 2016 the things on Google tester aren't changed much, even we implemented the critical css, requirejs, preloadCss, loadFont.

**Comment by Paul424** [comment]
Sorry for reopening this issue again but i'm struggling with a same issue; PSI tells me that my main css bundle; which i try to lazy load using LoadCSS is still blocking rendering above the fold. I expect LoadCSS is actually working but there may be some styles missing from the criticalcss? Already tried to reorder the criticalcss / loadcss but that did not help.

How would i approach this issue?

Site: https://www.hellolodge.net

Another question is that the webpage referred in this thread (https://developers.google.com/speed/pagespeed/insights/?url=filamentgroup.com&tab=mobile) does not seem to inline the LoadCSS, how is that? What better on that solution?

Thanks for advise!
Paul

**Comment by fatjester** [comment]
You are calling fonts that you don't have loaded yet (specifically: font-family: 'Oleo Script',Impact).  Render blocking means that you doing something that pauses the rendering of the page while the browser waits for items to download - that can be loading css (which this library addresses), but it can also be loading javascript, or referencing a font that doesn't exist.

By referencing a font that isn't loaded yet - the browser waits for a bit for the font to load (and triggers the warning in google pagespeed), then if it gets the font, continues rendering, and if not continues with the fallback.

To address it, you'd need to set the fonts for items to use system fonts (like serif or sans-serif), then use something like https://github.com/bramstein/fontfaceobserver to change those to your custom fonts once loaded.

Many people don't like doing this because it cases FOUT (https://css-tricks.com/fout-foit-foft/).

There may be other issues in addition to this, but this one being referenced specifically by Google in the Optimize CSS.

Good luck!

**Comment by Paul424** [comment]
Hi, I removed the css refering to that webfont however i still have PSI conplaining about javascipr & css above the fold. That question that i have is actually how i can see "what" is blocking the rendering? I'm using typekit for async loading of the webfonts and these are referred only in the non-critical css (loaded by loadcss).
Paul

**Comment by fatjester** [comment]
I don't know, no one said it was easy ;)
If you use chrome dev tools, you can throttle your load speed to to "slow 3g", and see how your page renders in a very slow environment (which is what google pagespeed is partially grading).

It still appears tied to how you are loading and displaying the Oleo Script items as at very slow speeds they don't render until the font has loaded (and it's still specifically referenced by the test).  I do note that you intentionally have those items hidden until that point, and that may still be what they are dinging you on.

Imagine if you were on a train, and your slow internet started to download this page, but then lost it's connection before it completed.  Some text would never render for people (because rendering was "blocked"), and that's how google is judging you on this.

**Comment by Paul424** [comment]
But that would mean that you can never pass the render blocking test when using webfonts above the fold? (unless obviously you would inline the font). Some working examples would help here, i'll try to search for those...

**Comment by Paul424** [comment]
just to give some more information/progress:
- I was able to get rid of the font issue (Oleo Script being mentioned as blocking page render) by replacing the solution from Typekit (webfontloader) with fontfaceobserver, and in addition i'm not hiding that font initially, but found Arial/Bold an acceptable fallback (for now).
- Also i was hiding the css rules for the webfont from the criticalcss even when it's only used below the font-event classes as set by .js but that is not required appearently.
- I'm still having an issue with the main css bundle being mentioned to block rendering, no idea what is missing from the criticalcss...

I expect the PSI somehow compares "screenshots" after each resource is loaded/rendered, when the difference exceeds a certain threshold then that resource is mentioned as blocking, can someone confirm this? It would make sense giving the results i'm seeing, for instance i have a lazy background and select2.js showing placeholder and icons that only becomes visible after... well.... after the bundle css and .js. So the difference is pretty large there...

Paul

**Comment by fatjester** [comment]
Still sounds like a font issue.
Likely icon fonts (Glyphicons), are at least one of these

**Comment by scottjehl** [comment]
Thanks for the discussion, folks. Just to chime in as a maintainer on this project: we think PSI is a great and useful tool, but the ultimate goal of this script is to provide a better experience for users. It's always hard to tell from the thread here, but it sounds like PSI sometimes has trouble identifying whether a loading sequence is actually render-blocking or not, which would be unfortunate, but unrelated to loadCSS or real-world users. Alternatively, perhaps PSI is properly identifying a blocking sequence, and you may need to use other tools to find a remedy. 

As @fatjester mentioned, there are some good tools out there to independently verify and examine that your loading process is working as expected, and that can tell you if PSI's warning is worth worrying about or not. Chrome's devtools are certainly handy. We would also recommend using webpagetest.org and its timeline view for validation in this regard, as you can break things down to see a nice stepped keyframe view of the page loading process, and the waterfall views can help you identify problematic loading sequences. 

Since this one has seemed to be a PSI issue all along, I'm inclined to lock down comments, assuming it does not appear that any action is required on our end. But if I'm missing something particular to loadCSS, we'd want to address it.

**Comment by fatjester** [comment]
Agreed.  I think it's been fully verified that loadCSS is working properly, and it's other issues triggering PSI.  It's almost always a font issue triggering PSI, so maybe some additions to the documentation and samples will help keep the issues down.

**Comment by Paul424** [comment]
@scottjehl I agree with you, and in fact i didn't want to hijack this issue to start a PSI knowledge thread but thing is that solutions such as loadcss, criticalcss, fontfaceobserver are so very close related that i'm having trouble identifying the boundaries between them... It would help (if i may suggest) to add a paragraph to the documentation how you can verify that loadcss is working properly.
Paul

**Comment by Littlemad** [comment]
@scottjehl I am sorry to say that PSI is an issue for me in my company where they want to get high value in PSI to get a better ranking value in the Google search results. If there was a way to communicate with people at Google about the issue would be great. As well I agree that we need a tool indipendent from PSI to verify 100% of time that loadCSS is working. At the moment I don't find it personally clear on how to test it on the network speed on google developer tool.

**Comment by BroFox86** [comment]
In my case loadCSS actually was not a blocking script. After i implemented design images of my site through CSS and deleted HTML comments before minification, PSI gave out a much better rating and ceased  to complain of blocking. Sorry for my English. I hope my solution will help someone.

**Comment by developer-lindner** [comment]
That's what PSI show me right now:

<img width="309" alt="bildschirmfoto 2017-12-06 um 09 13 44" src="https://user-images.githubusercontent.com/5435866/33651356-d65758fa-da65-11e7-8378-f047f4fc23e9.png">

It even duplicates although there are no duplicate includes?!

**Comment by nurtureJamesTan** [comment]
we have the same duplicate issue, is this got to do with page insight bug?

**Comment by jan-dh** [comment]
+1, getting false positives duplicates from PSI

**Comment by rsteinwand** [comment]
No blocking on any of my pages that I know of, but I'm only loading one stylesheet. https://www.intercepteft.com/searchsite.html

The only way I know of to determine if it's a false positive is to inline your entire stylesheet, then postload it. 

Those of you with blocking, how many stylesheets are you loading?
